criaCartao(
    ‘Geografia’,
    ‘Qual é a capital do Brasil?’,
    ‘Brasília.’)
    criaCartao(
    ‘Geografia’,
    ‘Qual é o maior continente do mundo?’,
    ‘Ásia.’)
    criaCartao(
    ‘Geografia’,
    ‘Em qual continente fica o Egito?’,
    ‘África.’)
    criaCartao(
    ‘Geografia’,
    ‘Qual é o nome do oceano que banha a costa oeste dos Estados Unidos?’,
    ‘Oceano Pacífico.’)
    criaCartao(
    ‘Geografia’, 
    ‘Qual é o maior país do mundo em área territorial?’,
    ‘Rússia.’)
    criaCartao(
    ‘Geografia’, 
    ‘Onde está localizado o Monte Everest?’,
    ‘Na fronteira entre o Nepal e o Tibete (China).’)
    criaCartao(
    ‘Geografia’, 
    ‘Qual é o nome do rio mais longo do mundo?’,
    ‘O rio Amazonas (embora haja debates, o Amazonas e o Nilo são frequentemente mencionados como os mais longos).’)
    criaCartao(
    ‘Geografia’, 
    ‘Em que país fica a Grande Muralha da China?’,
    ‘China.’)
    criaCartao(
    ‘Geografia’, 
    ‘Qual é a capital da França?’,
    ‘Paris.’)
    criaCartao(
    ‘Geografia’, 
    ‘O que é o Meridiano de Greenwich?’,
    ‘É o meridiano de 0° de longitude, que passa pela cidade de Greenwich, na Inglaterra.’)
    criaCartao(
    ‘Geografia’, 
    ‘Qual é o nome do deserto mais árido do mundo?’,
    ‘Deserto de Atacama.’
    criaCartao(
    ‘Geografia’, 
    ‘Em qual continente está a Austrália?’,
    ‘Oceania.’)
    criaCartao(
    ‘Geografia’, 
    ‘Qual é o nome do maior lago do mundo em volume de água?’,
    ‘Lago Baikal (Rússia).’)
    criaCartao(
    ‘Geografia’, 
    ‘Qual país tem a maior população do mundo?’,
    ‘China.’)
    criaCartao(
    ‘Geografia’, 
    ‘Em que continente está localizado o Japão?’,
    ‘Ásia.’)
    criaCartao(
    ‘Geografia’, 
    ‘Qual é o nome do continente que tem mais países?’,
    ‘África.’)
    criaCartao(
    ‘Geografia’, 
    ‘Qual é a capital da Argentina?’,
    ‘Buenos Aires.’)
    criaCartao(
    ‘Geografia’, 
    ‘O que é um paralelo na geografia?’,
    ‘São linhas imaginárias que correm de leste a oeste e que são paralelas ao Equador.’)
    criaCartao(
    ‘Geografia’,
    ‘Qual é a maior ilha do mundo?’,
    ‘Groenlândia.’)
    criaCartao(
    ‘Geografia’, 
    ‘Qual é o nome do mar que banha a costa leste do Brasil?’,
    ‘Oceano Atlântico.’)